
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4android.example.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedResaa965fc implements EmbeddedRes {

    @Override
    public String path() {
        return "/application-debug.properties";
    }

    @Override
    public int size() {
        return 71;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("5b64656275675d0d0a20202020656e61626c65643d310d0a20");
        out.append("2020206c6f672d617267756d656e74733d310d0a202020206c");
        out.append("6f672d70726f706572746965733d310d0a20202020");

    }
}
