
////////////////////////////////////////////////////////////////////////////////
// this file is generated by s4jer
// s4jer is a tool to embed resource in java code
//
// home page of s4jer:
//      https://github.com/starter-go/starter4j/tools/s4jer
//
// params:
//      package_name
//      class_name
//      data_size
//      res_path
//      for_list_1
////////////////////////////////////////////////////////////////////////////////

package com.bitwormhole.starter4android.example.res.m;

import com.bitwormhole.starter4j.application.resources.EmbeddedRes;

final class EmbeddedRes880689d implements EmbeddedRes {

    @Override
    public String path() {
        return "/application.properties";
    }

    @Override
    public int size() {
        return 117;
    }

    @Override
    public void hex(StringBuilder out) {
        
        // out.append("0123456789abcdef");

        
        out.append("0d0a5b6170706c69636174696f6e5d0d0a2020202070726f66");
        out.append("696c65732e6163746976653d64656275670d0a0d0a5b646562");
        out.append("75675d0d0a20202020656e61626c65643d310d0a202020206c");
        out.append("6f672d617267756d656e74733d310d0a202020206c6f672d70");
        out.append("726f706572746965733d310d0a20202020");

    }
}
